# Generated by Django 4.2.13 on 2024-06-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf_file',
        ),
    ]
