# Generated by Django 4.2.13 on 2024-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0004_alter_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
