# Generated by Django 4.2.13 on 2024-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0008_alter_chatsessionconversation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionconversation',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
