# Generated by Django 4.2.13 on 2024-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0009_chatsessionconversation_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionconversation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
